// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimpleTest.proto

package com.example;

public final class SimpleTestOuterClass {
  private SimpleTestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_SimpleTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_SimpleTest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_SimpleTest_ValueMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_SimpleTest_ValueMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_SimpleTest_InnerMessageTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_SimpleTest_InnerMessageTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SimpleTest.proto\022\013com.example\"\240\004\n\nSimp" +
      "leTest\022\013\n\003uid\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\025\n\rcat" +
      "egory_type\030\003 \001(\005\022\017\n\007content\030\004 \001(\014\022\r\n\005pri" +
      "ce\030\005 \001(\001\0228\n\tvalue_map\030\006 \003(\0132%.com.exampl" +
      "e.SimpleTest.ValueMapEntry\022;\n\tvalue_arr\030" +
      "\007 \003(\0132(.com.example.SimpleTest.InnerMess" +
      "ageTest\0222\n\ncorpus_int\030\010 \001(\0162\036.com.exampl" +
      "e.SimpleTest.Corpus\0222\n\ncorpus_str\030\t \001(\0162" +
      "\036.com.example.SimpleTest.Corpus\032Y\n\rValue" +
      "MapEntry\022\013\n\003key\030\001 \001(\003\0227\n\005value\030\002 \001(\0132(.c" +
      "om.example.SimpleTest.InnerMessageTest:\002" +
      "8\001\032*\n\020InnerMessageTest\022\n\n\002v1\030\001 \001(\003\022\n\n\002v2" +
      "\030\002 \001(\005\"Z\n\006Corpus\022\r\n\tUNIVERSAL\020\000\022\007\n\003WEB\020\001" +
      "\022\n\n\006IMAGES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEWS\020\004\022\014\n\010PRO" +
      "DUCTS\020\005\022\t\n\005VIDEO\020\007B\017\n\013com.exampleP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_SimpleTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_SimpleTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_SimpleTest_descriptor,
        new java.lang.String[] { "Uid", "Name", "CategoryType", "Content", "Price", "ValueMap", "ValueArr", "CorpusInt", "CorpusStr", });
    internal_static_com_example_SimpleTest_ValueMapEntry_descriptor =
      internal_static_com_example_SimpleTest_descriptor.getNestedTypes().get(0);
    internal_static_com_example_SimpleTest_ValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_SimpleTest_ValueMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_example_SimpleTest_InnerMessageTest_descriptor =
      internal_static_com_example_SimpleTest_descriptor.getNestedTypes().get(1);
    internal_static_com_example_SimpleTest_InnerMessageTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_SimpleTest_InnerMessageTest_descriptor,
        new java.lang.String[] { "V1", "V2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
