// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimpleTest.proto

package com.example;

public interface SimpleTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.SimpleTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 uid = 1;</code>
   * @return Whether the uid field is set.
   */
  boolean hasUid();
  /**
   * <code>optional int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 category_type = 3;</code>
   * @return Whether the categoryType field is set.
   */
  boolean hasCategoryType();
  /**
   * <code>optional int32 category_type = 3;</code>
   * @return The categoryType.
   */
  int getCategoryType();

  /**
   * <code>optional bytes content = 4;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>optional bytes content = 4;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>optional double price = 5;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <code>optional double price = 5;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>map&lt;int64, .com.example.SimpleTest.InnerMessageTest&gt; value_map = 6;</code>
   */
  int getValueMapCount();
  /**
   * <code>map&lt;int64, .com.example.SimpleTest.InnerMessageTest&gt; value_map = 6;</code>
   */
  boolean containsValueMap(
      long key);
  /**
   * Use {@link #getValueMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, com.example.SimpleTest.InnerMessageTest>
  getValueMap();
  /**
   * <code>map&lt;int64, .com.example.SimpleTest.InnerMessageTest&gt; value_map = 6;</code>
   */
  java.util.Map<java.lang.Long, com.example.SimpleTest.InnerMessageTest>
  getValueMapMap();
  /**
   * <code>map&lt;int64, .com.example.SimpleTest.InnerMessageTest&gt; value_map = 6;</code>
   */

  /* nullable */
com.example.SimpleTest.InnerMessageTest getValueMapOrDefault(
      long key,
      /* nullable */
com.example.SimpleTest.InnerMessageTest defaultValue);
  /**
   * <code>map&lt;int64, .com.example.SimpleTest.InnerMessageTest&gt; value_map = 6;</code>
   */

  com.example.SimpleTest.InnerMessageTest getValueMapOrThrow(
      long key);

  /**
   * <code>repeated .com.example.SimpleTest.InnerMessageTest value_arr = 7;</code>
   */
  java.util.List<com.example.SimpleTest.InnerMessageTest> 
      getValueArrList();
  /**
   * <code>repeated .com.example.SimpleTest.InnerMessageTest value_arr = 7;</code>
   */
  com.example.SimpleTest.InnerMessageTest getValueArr(int index);
  /**
   * <code>repeated .com.example.SimpleTest.InnerMessageTest value_arr = 7;</code>
   */
  int getValueArrCount();
  /**
   * <code>repeated .com.example.SimpleTest.InnerMessageTest value_arr = 7;</code>
   */
  java.util.List<? extends com.example.SimpleTest.InnerMessageTestOrBuilder> 
      getValueArrOrBuilderList();
  /**
   * <code>repeated .com.example.SimpleTest.InnerMessageTest value_arr = 7;</code>
   */
  com.example.SimpleTest.InnerMessageTestOrBuilder getValueArrOrBuilder(
      int index);

  /**
   * <code>optional .com.example.SimpleTest.Corpus corpus_int = 8;</code>
   * @return Whether the corpusInt field is set.
   */
  boolean hasCorpusInt();
  /**
   * <code>optional .com.example.SimpleTest.Corpus corpus_int = 8;</code>
   * @return The corpusInt.
   */
  com.example.SimpleTest.Corpus getCorpusInt();

  /**
   * <code>optional .com.example.SimpleTest.Corpus corpus_str = 9;</code>
   * @return Whether the corpusStr field is set.
   */
  boolean hasCorpusStr();
  /**
   * <code>optional .com.example.SimpleTest.Corpus corpus_str = 9;</code>
   * @return The corpusStr.
   */
  com.example.SimpleTest.Corpus getCorpusStr();
}
